### PR TITLE
Gonzalo Ruiz Sprint 1

### PR DESCRIPTION
**Pull request by GonJRuiz**

### CODE REVIEW

**Comment by dansmyers** [comment]
First part looks fine.

It appears that you're missing the last part of the campus connections problem. There's some code to determine the number of unique connections per student, but I can't tell if it's finished and it doesn't produce a distribution. Your boxplot of class sizes is also mislabeled as a histogram.

Finish the last part and I'll give you credit for the project.

**Comment by GonJRuiz** [comment]
Good afternoon Prof. Myers,

I believe I made the necessary changes to change the label from histogram to boxplot and I fixed the naming of a variable which I typed incorrectly in the code.

Hope it works better now.

Gonzalo Ruiz
________________________________

**Comment by dansmyers** [comment]
I don't see any solutions to the Sprint 2 problems?

**Comment by GonJRuiz** [comment]
Hello Dr. Myers,

I apologize for the inconvenience, I certainly did it because I worked on it with Jay Jiranek and TJ Donahue. I might've not created the pull request properly.

Best,
Gonzalo Ruiz
________________________________

**Comment by GonJRuiz** [comment]
Hello again Dr. Myers,

I have now retried to submit the assignment and I hope you received it this time. Could you let me know if there have been any issues? I don't understand why it never submitted the file but I had worked with my peers in order to submit it.

Gonzalo Ruiz
________________________________

**Review by GonJRuiz — COMMENTED** [review]
I believe this is the updated file for Sprint 2

**Comment by dansmyers** [comment]
Thanks for making the updates. I've marked your credit for this project.

**Pull request closed without merging**
