### PR TITLE
Gonzalo Ruiz Sprint 4 Deliverables

### PR DESCRIPTION
**Pull request by GonJRuiz**

### CODE REVIEW

**Comment by dansmyers** [comment]
Your written answers for Sprints 3 and 4 look fine, but the programming problems are incomplete. There is some code, but it's hard to understand given how it's mixed in with the rest of the problem description, there are no plots, and I can't find any evidence that you completed the M/M/1 simulator or the confidence interval problem.

**Comment by GonJRuiz** [comment]
Hello Dr. Myers,

Could I send you the programs and plots through email? They worked on my end I just had some trouble because my computer kept crashing when I tried to upload it to git.

I apologize for the inconvenience.

Gonzalo Ruiz
________________________________

**Comment by dansmyers** [comment]
Okay. Send them to me here.

Dan S. Myers, Ph.D.
Dept. of Mathematics and Computer Science
Rollins College
1000 Holt Ave. - 2743
Winter Park, FL 32789
(407)-646-2151
________________________________

**Comment by GonJRuiz** [comment]
________________________________

**Comment by dansmyers** [comment]
Sorry, I guess they don't come through on the GitHub message.

Send them as attachments to my regular e-mail address (dmyers@rollins.edu).


Dan S. Myers, Ph.D.
Dept. of Mathematics and Computer Science
Rollins College
1000 Holt Ave. - 2743
Winter Park, FL 32789
(407)-646-2151
________________________________

**Pull request closed without merging**
